### ISSUE TITLE
Can't make it past ./configure

### ISSUE THREAD

**Issue by ZergeiW72** [onkelDead/tascam-gtk#19] opened 2021-07-09 19:59 UTC
Hi ...

I'm stuck on this ...

./configure

configure: error: Package requirements (libxml++-2.6) were not met:

No package 'libxml++-2.6' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables XML2_CFLAGS
and XML2_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by Maxi98se** [comment] 2022-05-22 21:40
Hi,
I have the same problem. Have you found a solution?

**Comment by es02** [comment] 2022-06-22 04:49
Depending on what distro you use and its package naming conventions you probably want something named libxml++-devel

**Comment by onkelDead** [comment] 2024-12-15 17:51
nowadays the configure is able to deal with multiple revisions of xml++
I'll close this issue here and advice you to reopen it, if the issue is still present.

**Comment by onkelDead** [comment] 2024-12-15 17:52
closed by intention

**Closed by onkelDead** 2024-12-15 17:51 UTC

**Comment by be1** [comment] 2024-12-16 21:06
@ZergeiW72 and @Maxi98se  as say @es02 you have tin install libxml++ devel package with your distro's package manager. Which distro do you have ?
On Debian or Debian-related it's just a matter of: `sudo apt install libxml++2.6-dev`
On Arch or Arch-related, the package name is `libxml++2.6`
